blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³
    url: https://github.com/RsPYP/GoalCategorizationDiary/discussions
    about: è³ªå•ã‚„ä¸€èˆ¬çš„ãªè­°è«–ã¯ã“ã¡ã‚‰ã§
  - name: ğŸ“š ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
    url: https://github.com/RsPYP/GoalCategorizationDiary/blob/develop/README.md
    about: ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆã®è©³ç´°æƒ…å ±ã¨ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—ã‚¬ã‚¤ãƒ‰